name: Setup XFCE Runner + Tailscale

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-gui-runner:
    runs-on: ubuntu-latest
    env:
      TAILSCALE_AUTHKEY: ${{ vars.AUTHKEY }}
      USERNAME: runner
      PASSWORD: runner
      TAILSCALE_HOSTNAME: gh-xfce-${{ github.run_id }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- 1. RESTORE CACHE ---
      - name: Restore APT packages Cache
        uses: actions/cache@v4
        id: cache-restore
        with:
          path: /var/cache/apt/archives
          # Kunci yang stabil untuk paket
          key: ${{ runner.os }}-apt-xfce-xrdp-tailscale-v1
          restore-keys: |
            ${{ runner.os }}-apt-xfce-xrdp-tailscale-
            ${{ runner.os }}-apt-
      
      # --- SETUP USER & SUDO ---
      - name: Ensure runner user has sudo
        run: |
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USERNAME}

      # --- INSTALASI TAILSCALE REPOSITORY ---
      - name: Install Tailscale repository
        run: |
          echo ">>> Installing Tailscale Repository..."
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          
      # --- INSTALASI XFCE, XRDP, DAN TAILSCALE CLIENT (TERMASUK PERBAIKAN LAYAR HITAM) ---
      - name: Install XFCE, xrdp, and Tailscale client & Fix Black Screen
        run: |
          echo ">>> Installing lightweight XFCE Desktop, xrdp, and Tailscale client..."
          sudo apt-get update -qq

          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
            xfce4 xfce4-goodies xorg dbus-x11 xrdp tailscale

          # --- PERBAIKAN LAYAR HITAM (KONFIGURASI SESI XFCE) ---
          XFCE_CONFIG="/home/${USERNAME}/.xsession"
          
          echo "#!/bin/bash" | sudo tee ${XFCE_CONFIG}
          echo "export DISPLAY=:1" | sudo tee -a ${XFCE_CONFIG}
          echo "export XDG_SESSION_TYPE=x11" | sudo tee -a ${XFCE_CONFIG}
          echo "export XDG_CURRENT_DESKTOP=XFCE" | sudo tee -a ${XFCE_CONFIG}
          echo "exec startxfce4" | sudo tee -a ${XFCE_CONFIG}
          
          sudo chmod +x ${XFCE_CONFIG}
          sudo chown ${USERNAME}:${USERNAME} ${XFCE_CONFIG}
          
          sudo rm -f /etc/skel/.xsession
          echo "xfce4-session" | sudo tee /etc/skel/.xsession
          
          # Arahkan xrdp untuk selalu menggunakan XFCE saat memulai sesi
          sudo sed -i 's/exec startxfce4/xfce4-session/g' /etc/xrdp/startwm.sh
          # --- AKHIR PERBAIKAN ---

          sudo systemctl enable --now xrdp
          sudo systemctl restart xrdp

      # --- KONFIGURASI TAILSCALE ---
      - name: Start Tailscale
        run: |
          echo ">>> Starting Tailscale..."
          sudo tailscale up --authkey "${TAILSCALE_AUTHKEY}" --hostname "${TAILSCALE_HOSTNAME}"

      # --- INFO KONEKSI & KEEP ALIVE ---
      - name: Connection Info + Keep Alive
        id: keep-alive
        run: |
          echo "=== FINAL CONNECTION INFO ==="
          echo "USERNAME: ${USERNAME}"
          echo "PASSWORD: ${PASSWORD}"
          echo "Tailscale IPs:"
          sudo tailscale ip -4
          echo
          echo ">>> Connect with any RDP client using the IP above (port 3389)."
          echo ">>> Keeping runner alive until manually cancelled..."
          while true; do
            sleep 300
          done
      - name: Clean up apt cache
        run: |
          sudo rm -f /var/cache/apt/archives/lock
          sudo rm -f /var/lib/apt/lists/lock
          sudo rm -rf /var/cache/apt/archives/partial
          sudo rm -rf /var/lib/apt/lists/partial
      # --- 2. SAVE CACHE KONDISIONAL (TERPERBAIKI!) ---
      - name: Save APT packages Cache (ALWAYS RUN)
        uses: actions/cache/save@v4
        if: always()
        with:
          path: /var/cache/apt/archives
          # Kunci yang sama dengan langkah restore untuk menghindari warning!
          key: ${{ runner.os }}-apt-xfce-xrdp-tailscale-v1
