# ... Bagian awal tetap sama ...
name: Setup XFCE Runner + Tailscale + noVNC

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-gui-runner:
    runs-on: ubuntu-latest
    env:
      TAILSCALE_AUTHKEY: ${{ vars.AUTHKEY }}
      USERNAME: runner
      PASSWORD: runner
      TAILSCALE_HOSTNAME: gh-xfce-vnc-${{ github.run_id }}
      VNC_PORT: 5902
      WEBSOCKET_PORT: 6080
      RDP_PORT: 3390

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # --- SETUP USER & SUDO (Tetap) ---
      - name: Ensure runner user has sudo
        run: |
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USERNAME}
      - name: Grant permissions to APT cache
        run: |
          sudo chown -R $USER:$USER /var/cache/apt
          sudo chown -R $USER:$USER /var/lib/apt
          echo "set man-db/auto-update false" | debconf-communicate
          dpkg-reconfigure man-db
          
      # --- 1. RESTORE CACHE (Tetap) ---
      - name: Restore APT packages Cache
        if: always()
        uses: actions/cache@v4
        id: cache-restore
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-xfce-vnc-tailscale-v1
          restore-keys: |
            ${{ runner.os }}-apt-xfce-vnc-tailscale-
            ${{ runner.os }}-apt-

      # ⭐⭐⭐ PANGGILAN SKRIP TUNGGAL ⭐⭐⭐
      - name: Run All-in-One Setup Script (Install, Configure, Start Services)
        if: always()
        id: setup-and-start
        run: chmod +x ./setup_gui_runner.sh && sudo -E ./setup_gui_runner.sh
      - name: Keep Runner Alive (Cancel to Stop)
        run: |
          echo ">>> Runner berjalan. Batalkan (Cancel) workflow secara manual untuk menghentikan."
          while true; do
            sleep 300
          done
      # ... Bagian Clean up dan Save Cache (Tetap) ...
      - name: Clean up apt cache
        if: always()
        run: |
          sudo rm -f /var/cache/apt/archives/lock
          sudo rm -f /var/lib/apt/lists/lock
          sudo rm -rf /var/cache/apt/archives/partial
          sudo rm -rf /var/lib/apt/lists/partial
          sudo rm -rf /var/cache/debconf/config.dat-new
          sudo rm -rf /var/cache/debconf/passwords.dat
      
      - name: Save APT packages Cache (ALWAYS RUN)
        uses: actions/cache/save@v4
        if: always()
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-xfce-vnc-tailscale-v1
