name: Setup XFCE Runner + Tailscale

on:
  # Memungkinkan untuk menjalankan workflow secara manual dari GitHub web UI
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-gui-runner:
    runs-on: ubuntu-latest
    env:
      # Variabel lingkungan
      TAILSCALE_AUTHKEY: ${{ vars.AUTHKEY }}
      USERNAME: runner
      PASSWORD: runner
      TAILSCALE_HOSTNAME: gh-xfce-${{ github.run_id }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- 1. RESTORE CACHE ---
      - name: Restore APT packages Cache
        uses: actions/cache@v4
        id: cache-restore
        with:
          path: /var/cache/apt/archives
          # Kunci yang stabil untuk paket XFCE/xrdp/Tailscale
          key: ${{ runner.os }}-apt-xfce-xrdp-tailscale-v1
          restore-keys: |
            ${{ runner.os }}-apt-xfce-xrdp-tailscale-
            ${{ runner.os }}-apt-
      
      # --- SETUP USER & SUDO ---
      - name: Ensure runner user has sudo
        run: |
          # Mengatur password dan memberikan izin sudo NOPASSWD untuk user runner
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USERNAME}

      # --- INSTALASI TAILSCALE REPOSITORY ---
      - name: Install Tailscale repository
        # Menambahkan repo APT Tailscale. Ini tidak di-cache.
        run: |
          echo ">>> Installing Tailscale Repository..."
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          
      # --- INSTALASI XFCE, XRDP, DAN TAILSCALE CLIENT ---
      - name: Install XFCE, xrdp, and Tailscale client
        run: |
          echo ">>> Installing lightweight XFCE Desktop, xrdp, and Tailscale client..."
          sudo apt-get update -qq

          # apt-get akan menggunakan cache jika tersedia
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
            xfce4 xfce4-goodies xorg dbus-x11 xrdp tailscale

          # set up xfce user
          echo "startxfce4" | sudo tee /home/${USERNAME}/.xsession
          sudo chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.xsession
          
          # make xrdp use xfce
          echo "exec startxfce4" | sudo tee /etc/skel/.xsession
          echo "startxfce4" | sudo tee /etc/skel/.xinitrc

          # Aktifkan dan mulai ulang xrdp service
          sudo systemctl enable --now xrdp
          sudo systemctl restart xrdp

      # --- KONFIGURASI TAILSCALE ---
      - name: Start Tailscale
        run: |
          echo ">>> Starting Tailscale..."
          sudo tailscale up --authkey "${TAILSCALE_AUTHKEY}" --hostname "${TAILSCALE_HOSTNAME}"

      # --- INFO KONEKSI & KEEP ALIVE ---
      - name: Connection Info + Keep Alive
        id: keep-alive
        run: |
          echo "=== FINAL CONNECTION INFO ==="
          echo "USERNAME: ${USERNAME}"
          echo "PASSWORD: ${PASSWORD}"
          echo "Tailscale IPs:"
          sudo tailscale ip -4
          echo
          echo ">>> Connect with any RDP client using the IP above (port 3389)."
          echo ">>> Keeping runner alive until manually cancelled..."
          # Jaga runner tetap berjalan. Pembatalan akan memicu langkah cache berikutnya.
          while true; do
            sleep 300
          done
          
      # --- 2. SAVE CACHE KONDISIONAL (PENTING!) ---
      - name: Save APT packages Cache (ALWAYS RUN)
        uses: actions/cache/save@v4
        # Kunci PENTING: selalu jalankan langkah ini, bahkan jika job dibatalkan atau gagal!
        if: always()
        with:
          path: /var/cache/apt/archives
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
