name: Setup XFCE Runner + Tailscale

on:
  # Memungkinkan untuk menjalankan workflow secara manual dari GitHub web UI
  workflow_dispatch:

permissions:
  # Hanya perlu izin read untuk checkout kode
  contents: read

jobs:
  setup-gui-runner:
    runs-on: ubuntu-latest
    env:
      # Variabel lingkungan yang digunakan di seluruh job
      TAILSCALE_AUTHKEY: ${{ vars.AUTHKEY }}
      USERNAME: runner
      PASSWORD: runner
      TAILSCALE_HOSTNAME: gh-xfce-${{ github.run_id }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- CACHING APT PACKAGES ---
      - name: Cache APT packages
        # Direktori ini menyimpan semua file .deb yang diunduh APT.
        # Jika cache ditemukan, langkah instalasi akan jauh lebih cepat.
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          # Kunci yang dibuat unik. Ubah 'v1' menjadi 'v2' jika Anda menambah/mengubah paket.
          key: ${{ runner.os }}-apt-xfce-xrdp-tailscale-v1
          restore-keys: |
            ${{ runner.os }}-apt-xfce-xrdp-tailscale-
            ${{ runner.os }}-apt-

      # --- SETUP USER & SUDO ---
      - name: Ensure runner user has sudo
        run: |
          # Mengatur password dan memberikan izin sudo NOPASSWD untuk user runner
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USERNAME}

      # --- INSTALASI TAILSCALE REPOSITORY ---
      - name: Install Tailscale repository
        # Langkah ini menambahkan repo Tailscale, yang TIDAK di-cache, tetapi cepat
        run: |
          echo ">>> Installing Tailscale Repository..."
          curl -fsSL https://tailscale.com/install.sh | sudo sh

      # --- INSTALASI XFCE, XRDP, DAN TAILSCALE CLIENT ---
      - name: Install XFCE, xrdp, and Tailscale client
        run: |
          echo ">>> Installing lightweight XFCE Desktop, xrdp, and Tailscale client..."
          sudo apt-get update -qq

          # apt-get akan menggunakan cache (/var/cache/apt/archives) jika tersedia
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
            xfce4 xfce4-goodies xorg dbus-x11 xrdp tailscale

          # set up xfce user
          echo "startxfce4" | sudo tee /home/${USERNAME}/.xsession
          sudo chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.xsession

          # make xrdp use xfce
          echo "exec startxfce4" | sudo tee /etc/skel/.xsession
          echo "startxfce4" | sudo tee /etc/skel/.xinitrc

          # Aktifkan dan mulai ulang xrdp service
          sudo systemctl enable --now xrdp
          sudo systemctl restart xrdp

      # --- KONFIGURASI TAILSCALE ---
      - name: Start Tailscale
        run: |
          echo ">>> Starting Tailscale..."
          # Menggunakan AUTHKEY dari Secrets/Vars Anda untuk otentikasi
          sudo tailscale up --authkey "${TAILSCALE_AUTHKEY}" --hostname "${TAILSCALE_HOSTNAME}"

      # --- INFO KONEKSI & KEEP ALIVE ---
      - name: Connection Info + Keep Alive
        run: |
          echo "=== FINAL CONNECTION INFO ==="
          echo "USERNAME: ${USERNAME}"
          echo "PASSWORD: ${PASSWORD}"
          echo "Tailscale IPs:"
          # Tampilkan IP Tailscale untuk koneksi RDP
          IP_ADDR=$(sudo tailscale ip -4 | head -n1)
          echo "${IP_ADDR}"
          echo
          echo ">>> Connect with any RDP client using the IP above (port 3389)."
          echo ">>> Keeping runner alive for 10 minutes (600 seconds) to maintain RDP session..."
          # Jaga runner tetap berjalan (agar koneksi RDP stabil)
          while true; do
            sleep 600
          done
